# Generated by Django 3.0.7 on 2021-01-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
